/*Home ownership Vs last payment date stats*/

SELECT *FROM FINANCE_MAIN;
SELECT *FROM FINANCE_DETAILS;

SELECT HOME_OWNERSHIP,COUNT(LAST_PYMNT_D) AS NO_OF_LAST_PAYMENT_DATE FROM FINANCE_MAIN FM LEFT JOIN FINANCE_DETAILS FD ON FM.ID=FD.ID
GROUP BY  HOME_OWNERSHIP,LAST_PYMNT_D ORDER BY NO_OF_LAST_PAYMENT_DATE desc;