/*Grade and sub grade wise revol_bal*/

SELECT *FROM FINANCE_MAIN;
SELECT *FROM FINANCE_DETAILS;

SELECT GRADE,SUB_GRADE,SUM(REVOL_BAL) AS TOTAL_REVOL_BAL FROM FINANCE_MAIN FM LEFT JOIN FINANCE_DETAILS FD ON FM.ID=FD.ID
GROUP BY GRADE,SUB_GRADE ORDER BY GRADE,SUB_GRADE;