/*Year wise loan amount Stats*/

SELECT *FROM FINANCE_MAIN;

SELECT YEAR(ISSUE_D) AS YEAR_OF_ISSUE_D ,SUM(LOAN_AMNT) AS TOTAL_LOAN_AMNT FROM FINANCE_MAIN 
GROUP BY YEAR_OF_ISSUE_D ORDER BY TOTAL_LOAN_AMNT DESC ;