/*State wise and month wise loan status*/

SELECT *FROM FINANCE_MAIN;
SELECT ADDR_STATE,MONTHNAME(ISSUE_D)AS MONTH_OF_ISSUE_D,LOAN_STATUS FROM FINANCE_MAIN GROUP BY ADDR_STATE,MONTH_OF_ISSUE_D,LOAN_STATUS
 ORDER BY LOAN_STATUS;