/*Total Payment for Verified Status Vs Total Payment for Non Verified Status*/

SELECT *FROM FINANCE_MAIN;
SELECT *FROM FINANCE_DETAILS;

SELECT VERIFICATION_STATUS, CONCAT("$",FORMAT(SUM(TOTAL_PYMNT)/1000000,2),2,"M") AS TOTAL_PAYMENT FROM FINANCE_MAIN FM 
LEFT JOIN FINANCE_DETAILS FD ON FM.ID=FD.ID
GROUP BY VERIFICATION_STATUS ORDER BY TOTAL_PAYMENT;
